/**
 * @description Walks the live commander program tree and emits a single
 * `tagoio.1` roff page to stdout. The generated page is the source of truth
 * for `man tagoio` and for shell tab-completion (zsh/fish parse roff).
 *
 * Run via `npm run man`, which redirects stdout to `man/tagoio.1`. A vitest
 * snapshot test pins the output so any flag/command change without a matching
 * snapshot regen fails CI (see `scripts/generate-man.test.ts`).
 *
 * Roff special characters that must be escaped in user-supplied strings:
 *   `\`  → `\\`
 *   `-`  → `\-`   (so it survives nroff dehyphenation in option names)
 *   `.` at line start → `\&.` (otherwise read as a control directive)
 */
import { Command, Option } from "commander";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import { buildProgram } from "../index.js";

/** Reads the package.json that sits two levels up from `src/lib`. */
function readPackageJSON(): { name: string; version: string; description?: string } {
  const path = join(import.meta.dirname, "..", "..", "package.json");
  return JSON.parse(readFileSync(path, "utf8"));
}

/** Escapes a string for safe interpolation into roff body text. */
function escapeRoff(input: string): string {
  return input
    .replaceAll("\\", "\\\\")
    .replaceAll("-", "\\-")
    .replaceAll(/^\./gm, "\\&.");
}

/** Joins a list of lines into a single block, trimming trailing whitespace per line. */
function block(...lines: string[]): string {
  return `${lines.map((line) => line.replace(/[\t ]+$/u, "")).join("\n")}\n`;
}

/** Emits the page header (.TH) plus the static top sections. */
function buildHeader(version: string): string {
  return block(
    `.\\" Generated by scripts/generate-man.ts. Do not edit by hand.`,
    `.TH TAGOIO 1 "" "tagoio ${version}" "User Commands"`,
    "",
    ".SH NAME",
    "tagoio \\- command\\-line tool for TagoIO",
    "",
    ".SH SYNOPSIS",
    ".B tagoio",
    "[\\fIglobal options\\fR]",
    "\\fIcommand\\fR",
    "[\\fIcommand options\\fR]",
    "[\\fIarguments...\\fR]",
    "",
    ".SH DESCRIPTION",
    "The TagoIO Command Line Tool lets developers manage analyses,",
    "devices, dashboards, and profiles on TagoIO from the terminal.",
    "It follows clig.dev conventions: data on stdout, status messages",
    "(\\fB[INFO]\\fR, \\fB[OK]\\fR, \\fB[ERROR]\\fR) on stderr, and machine\\-readable",
    "JSON output via \\fB\\-\\-json\\fR.",
    "",
    ".SH GLOBAL OPTIONS",
    ".TP",
    ".BR \\-V , \" \\-\\-version\"",
    "Output the version number.",
    ".TP",
    ".BR \\-h , \" \\-\\-help\"",
    "Display help for command.",
  );
}

/** Emits the trailing static sections. */
function buildFooter(): string {
  return block(
    "",
    ".SH EXIT STATUS",
    ".TP",
    ".B 0",
    "Command completed successfully.",
    ".TP",
    ".B 1",
    "Any failure. The error is printed on stderr with an \\fB[ERROR]\\fR prefix",
    "(or as a JSON object when \\fB\\-\\-json\\fR is set).",
    "",
    ".SH ENVIRONMENT",
    ".TP",
    ".B TAGOIO_DEFAULT",
    "Selects which environment from \\fItagoconfig.json\\fR the CLI uses",
    "when no \\fB\\-\\-env\\fR flag is given. Persisted by",
    ".BR tagoio\\ set\\-env .",
    "",
    ".SH FILES",
    ".TP",
    ".I ./tagoconfig.json",
    "Project\\-level configuration. Created and updated by",
    ".BR tagoio\\ init .",
    ".TP",
    ".I ./.tago-lock.<env>.lock",
    "Per\\-environment profile token written by",
    ".BR tagoio\\ login .",
    "One file per environment, kept in the current project directory.",
    ".TP",
    ".I ./.tagoio/personal.env",
    "Persists the user's default environment selection",
    "(\\fBTAGOIO_DEFAULT\\fR). Updated by",
    ".BR tagoio\\ set\\-env .",
    "",
    ".SH SEE ALSO",
    "TagoIO documentation: \\fIhttps://help.tago.io\\fR",
    "",
    "Issue tracker: \\fIhttps://github.com/tago-io/tagoio-cli/issues\\fR",
    "",
    ".SH AUTHOR",
    "TagoIO LLC",
  );
}

/** Returns the placeholder a command's [arg] / <arg> tokens render as in the heading. */
function commandHeading(cmd: Command): string {
  const args = cmd.registeredArguments.map((arg) => {
    const name = arg.name();
    return arg.required ? `<${name}>` : `[${name}]`;
  });
  const headingTokens = [cmd.name(), ...args].join(" ");
  return escapeRoff(headingTokens);
}

/** Renders a single Option as a `.TP`-prefixed roff block. */
function renderOption(option: Option): string {
  // Commander gives us a flags string like `-t, --token <profile-token>`.
  // Split into the flag list and the optional argument placeholder.
  const flagsText = option.flags;
  const placeholderMatch = /\s+([<\[].+)$/u.exec(flagsText);
  const placeholder = placeholderMatch ? placeholderMatch[1] : "";
  const flagsOnly = placeholder ? flagsText.slice(0, flagsText.length - placeholder.length).trim() : flagsText;

  // Render each flag in bold; placeholder in italic.
  const flagTokens = flagsOnly
    .split(",")
    .map((flag) => `\\fB${escapeRoff(flag.trim())}\\fR`)
    .join(", ");
  const placeholderRendered = placeholder ? ` \\fI${escapeRoff(placeholder)}\\fR` : "";

  const description = option.description ? escapeRoff(option.description) : "";
  const defaultText = option.defaultValue !== undefined && option.defaultValue !== "" ? ` (default: ${escapeRoff(JSON.stringify(option.defaultValue))})` : "";

  return block(`.TP`, `${flagTokens}${placeholderRendered}`, `${description}${defaultText}` || "\\&");
}

/** Renders any text the command attached via `addHelpText("after", ...)` as a literal block. */
function renderAfterText(cmd: Command): string {
  // Commander 14 wires `addHelpText("after", text)` via `this.on("afterHelp", ...)`,
  // so the registered listeners live on Node's EventEmitter — accessible
  // through the public `listeners(eventName)` API. The Command typings don't
  // expose EventEmitter members, so we cast to the minimal shape we need.
  const emitter = cmd as unknown as { listeners(event: string): Array<(ctx: unknown) => void> };
  const listeners = emitter.listeners("afterHelp");
  if (listeners.length === 0) {
    return "";
  }

  // Each listener writes via `context.write(str)`. We capture those writes
  // by passing a stub context that appends to a buffer, then flatten.
  const captured: string[] = [];
  const stubContext = {
    error: false,
    command: cmd,
    write: (str: string) => {
      captured.push(str);
    },
  };

  for (const listener of listeners) {
    listener(stubContext);
  }

  if (captured.length === 0) {
    return "";
  }

  // Render the captured text as a roff `.nf` (no-fill) block so indentation
  // and line breaks survive the page layout.
  const lines = captured.join("\n").split("\n").map((line) => line.trimEnd());
  // Strip leading and trailing blank lines so the block sits flush.
  while (lines.length > 0 && lines[0] === "") {
    lines.shift();
  }
  while (lines.length > 0 && lines[lines.length - 1] === "") {
    lines.pop();
  }
  if (lines.length === 0) {
    return "";
  }

  const out: string[] = [".PP", ".nf"];
  for (const line of lines) {
    out.push(line.length === 0 ? "" : escapeRoff(line));
  }
  out.push(".fi");
  return block(...out);
}

/** Renders one command (registered top-level on `program`) as a `.SS` block. */
function renderCommand(cmd: Command): string {
  const heading = commandHeading(cmd);
  const description = cmd.description() ? escapeRoff(cmd.description()) : "";
  const sections: string[] = [block(`.SS ${heading}`, description || "\\&")];

  for (const option of cmd.options) {
    sections.push(renderOption(option));
  }

  const afterText = renderAfterText(cmd);
  if (afterText) {
    sections.push(afterText);
  }

  return sections.join("");
}

/**
 * @description Top-level entry point. Builds the program tree, walks it,
 * returns the full roff document as a string. Pure: no I/O, no env reads.
 */
function generateManPage(version: string, commands: readonly Command[]): string {
  const out: string[] = [buildHeader(version), block("", ".SH COMMANDS")];

  for (const cmd of commands) {
    // Skip the empty placeholder commands like `program.command("Devices Header")`
    // that the existing CLI uses as visual section dividers in --help.
    // Commander parses "Foo Header" as { name: "Foo", arg: <Header> }, so we
    // check both the name and the rendered heading (name + args).
    if (commandHeading(cmd).toLowerCase().includes("header")) {
      continue;
    }
    // Skip commander's auto-generated `help` subcommand — already covered by
    // GLOBAL OPTIONS (-h / --help).
    if (cmd.name() === "help") {
      continue;
    }
    out.push(renderCommand(cmd));
  }

  out.push(buildFooter());
  return out.join("");
}

/** Constructs a fresh program with every command registered, ready to walk. */
function buildPopulatedProgram(): Command {
  // The man-page reflects the static command surface, not any user's
  // current environment; pass an empty string so commander does not bake
  // a runtime value into the help output. `buildProgram` lives in
  // `src/index.ts` and is the single source of truth for the CLI's command
  // tree — adding a command there automatically appears in this generator's
  // output on the next run.
  return buildProgram("");
}

function main(): void {
  const pkg = readPackageJSON();
  const program = buildPopulatedProgram();
  const roff = generateManPage(pkg.version, program.commands);
  process.stdout.write(roff);
}

// Run when invoked directly (so tests can `import` the helpers without side effects).
const isMain = import.meta.url === `file://${process.argv[1]}` || import.meta.url.endsWith("/src/lib/generate-man.ts");
if (isMain) {
  main();
}

export { buildPopulatedProgram, escapeRoff, generateManPage };
