import { Account } from "@tago-io/sdk";
import { OTPType } from "@tago-io/sdk/out/modules/Account/account.types";
import prompts from "prompts";
import { errorHandler, highlightMSG, successMSG } from "../lib/messages";
import { writeToken } from "../lib/token";

function writeCustomToken(environment: string, token: string) {
  writeToken(token, environment);
  console.info(`Token writed to the environment ${environment}`);
}

interface LoginOptions {
  email?: string;
  password?: string;
  token?: string;
}

async function handleOTPLogin({ otp_autosend }: { otp_autosend: OTPType }, { email, password }: Required<LoginOptions>) {
  if (otp_autosend !== "authenticator") {
    await Account.requestLoginPINCode({ email, password }, otp_autosend).catch(errorHandler);
  }

  const pinCode = await prompts({ type: "text", message: `Enter your PINCODE [${otp_autosend}]: `, name: "value" });

  const loginResult = await Account.login({ email, password, otp_type: otp_autosend, pin_code: pinCode.value } as any).catch(errorHandler);
  if (loginResult) {
    return { ...loginResult, otp_type: otp_autosend, pin_code: pinCode.value };
  }
}

async function tagoLogin(environment: string, options: LoginOptions) {
  if (options.token) {
    return writeCustomToken(environment, options.token);
  }

  let { email, password } = options;

  if (!email) {
    const question = await prompts({ type: "text", name: "email", message: "Enter your TagoIO email: " });
    ({ email } = question);
    if (!email) {
      return;
    }
  }
  if (!password) {
    const question = await prompts({ type: "password", name: "password", message: "Enter your password: " });
    ({ password } = question);
    if (!password) {
      return;
    }
  }

  const loginResult = await Account.login({ email, password }).catch(async (error) => {
    try {
      const errorJSON = JSON.parse(error);
      if (errorJSON?.otp_enabled) {
        return handleOTPLogin(errorJSON, { email: email as string, password: password as string, token: "" }).catch(errorHandler);
      }
    } catch {
      //any
    }

    errorHandler(error);
  });

  if (!loginResult) {
    return;
  }

  const formatProfileName = (x: { name: string }) => `${x.name}${highlightMSG((x as any).from_share ? " [Shared with you]" : "")}`;

  const choices = loginResult.profiles.map((x) => ({ title: formatProfileName(x), value: x.id }));
  const profileQuestion = await prompts({ type: "autocomplete", choices, name: "id", message: "Which profile you want to choose? " });

  const result = await Account.tokenCreate({
    email,
    password,
    expire_time: "never",
    otp_type: (loginResult as any)?.otp_type || undefined,
    name: "Generated by TagoIO CLI",
    pin_code: (loginResult as any)?.pin_code || undefined,
    profile_id: profileQuestion.id,
  } as any).catch(errorHandler);

  if (!result) {
    return;
  }

  writeToken(result.token, environment);

  successMSG(`Token writed to the environment ${highlightMSG(environment)}`);
  options.token = result.token;
}

export { tagoLogin };
